using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SalesSaaS.Domain;
namespace SalesSaaS.Infrastructure.Configurations;
public sealed class SupplierConfiguration : IEntityTypeConfiguration<Supplier> { public void Configure(EntityTypeBuilder<Supplier> b) { b.HasIndex(x => new { x.TenantId, x.TaxId }).IsUnique(); b.Property(x => x.LegalName).HasMaxLength(150); b.Property(x => x.TaxId).HasMaxLength(20); } }
public sealed class PurchaseOrderConfiguration : IEntityTypeConfiguration<PurchaseOrder> { public void Configure(EntityTypeBuilder<PurchaseOrder> b) { b.Property(x => x.TotalAmount).HasPrecision(18,2); b.HasOne<Supplier>().WithMany().HasForeignKey(x => x.SupplierId).OnDelete(DeleteBehavior.Restrict); b.HasOne<Warehouse>().WithMany().HasForeignKey(x => x.WarehouseId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class PurchaseOrderItemConfiguration : IEntityTypeConfiguration<PurchaseOrderItem> { public void Configure(EntityTypeBuilder<PurchaseOrderItem> b) { b.Property(x => x.UnitCost).HasPrecision(18,2); b.Property(x => x.TotalAmount).HasPrecision(18,2); b.HasIndex(x => new { x.TenantId, x.PurchaseOrderId }); b.HasOne<PurchaseOrder>().WithMany(x => x.Items).HasForeignKey(x => x.PurchaseOrderId).OnDelete(DeleteBehavior.Restrict); b.HasOne<Product>().WithMany().HasForeignKey(x => x.ProductId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class PurchaseInvoiceConfiguration : IEntityTypeConfiguration<PurchaseInvoice> { public void Configure(EntityTypeBuilder<PurchaseInvoice> b) { b.HasIndex(x => new { x.TenantId, x.Number }).IsUnique(); b.Property(x => x.TotalAmount).HasPrecision(18,2); b.HasOne<PurchaseOrder>().WithMany().HasForeignKey(x => x.PurchaseOrderId).OnDelete(DeleteBehavior.Restrict); b.HasOne<Supplier>().WithMany().HasForeignKey(x => x.SupplierId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class SupplierAccountEntryConfiguration : IEntityTypeConfiguration<SupplierAccountEntry> { public void Configure(EntityTypeBuilder<SupplierAccountEntry> b) { b.Property(x => x.Amount).HasPrecision(18,2); b.HasOne<Supplier>().WithMany().HasForeignKey(x => x.SupplierId).OnDelete(DeleteBehavior.Restrict); b.HasOne<PurchaseInvoice>().WithMany().HasForeignKey(x => x.PurchaseInvoiceId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class CashRegisterSessionConfiguration : IEntityTypeConfiguration<CashRegisterSession> { public void Configure(EntityTypeBuilder<CashRegisterSession> b) { b.Property(x => x.OpeningBalance).HasPrecision(18,2); b.Property(x => x.ClosingBalance).HasPrecision(18,2); b.HasOne<Warehouse>().WithMany().HasForeignKey(x => x.WarehouseId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class CashMovementConfiguration : IEntityTypeConfiguration<CashMovement> { public void Configure(EntityTypeBuilder<CashMovement> b) { b.Property(x => x.Amount).HasPrecision(18,2); b.Property(x => x.Description).HasMaxLength(300); b.HasOne<CashRegisterSession>().WithMany().HasForeignKey(x => x.CashRegisterSessionId).OnDelete(DeleteBehavior.Restrict); } }
